/**
 * Anledningspakker fra prisarket, afsnit 5 (ANLEDNINGER) og 6 (ÅRSTIDER).
 *
 * Kilde: "LejHøjtaler Katalog.xlsx". Arket sætter dem sammen af enkeltdele og
 * lader prisen følge af delene — præcis som resten af kataloget gør nu, så der
 * står ingen priser i filen her.
 *
 * ALLE er hidden. En pakke uden sit eget foto er ikke klar til at blive vist:
 * et kort med et genbrugt løsdelsbillede ser ikke ud som de andre, og det er
 * værre end intet kort. De ligger i AFVENTER_FOTO og kan tændes én for én fra
 * /admin/produkter, når billedet er der.
 *
 * Arket havde 67 pakker i de to afsnit. 19 var det samme udstyr som en pakke,
 * der allerede fandtes (alle temafesterne er fx Festpakke 30-50), og to bestod
 * af ét enkelt produkt og er altså en rabat, ikke en pakke. Tilbage står de 46
 * herunder.
 */
import type { RawRentalProduct } from "./products";

/**
 * Kørsels-id'erne står skrevet ud, ikke importeret fra products.ts.
 * products.ts importerer denne fil, så en værdi den anden vej ville være en
 * rundkreds: DELIVERY_ADDON_IDS ville være undefined, når listen her bygges.
 */
const KOERSEL = ["levering_ud", "afhentning_retur", "levering_begge"];

export const anledningPakker: RawRentalProduct[] = [
  /* ── Arkets 5.1 Firmafest ── */
  {
    id: "anl_firmafest_basic",
    hidden: true,
    category: "lyd",
    image: "/images/product-soundboks-v2-white.webp",
    showPartImages: true,
    name_da: "Firmafest Basic",
    name_en: "Company Party Basic",
    desc_da: "Soundboks 4 og en lyseffekt. Musik og lidt farve til afdelingens fest.",
    desc_en: "A Soundboks 4 and one light effect. Music and a bit of colour for the department party.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Til firmafesten i kantinen eller på kontoret, hvor der ikke er strøm alle steder, og hvor lyden skal kunne flyttes.",
      usecase_en: "For the company party in the canteen or the office, where there is no power everywhere and the sound needs to move.",
      parts: [
        { productId: "soundboks", label_da: "Soundboks 4", label_en: "Soundboks 4", price: 695 },
        { productId: "lyseffekt", label_da: "Enkelt lyseffekt", label_en: "Single light effect", price: 195 },
      ],
    },
  },
  {
    id: "anl_firmafest_plus",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Firmafest Plus",
    name_en: "Company Party Plus",
    desc_da: "Mellem højtalerpakke på stativer og en lysbar. Lyd og lys til 30-50 kolleger.",
    desc_en: "The medium speaker package on stands with a light bar. Sound and light for 30-50 colleagues.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Firmafesten hvor der både skal holdes tale og danses, og hvor højtalerne skal op i ørehøjde.",
      usecase_en: "The company party with both speeches and dancing, where the speakers need to be at ear height.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
      ],
    },
  },
  {
    id: "anl_firmafest_deluxe",
    hidden: true,
    category: "lyd",
    image: "/images/product-hojtalerpakke-stor-white.webp",
    showPartImages: true,
    name_da: "Firmafest Deluxe",
    name_en: "Company Party Deluxe",
    desc_da: "Stor højtalerpakke, lysbar og fire uplights. Til salen med 50-100 kolleger.",
    desc_en: "The large speaker package, a light bar and four uplights. For the hall with 50-100 colleagues.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Den store firmafest i en lejet sal: bas nok til dansegulvet, og uplights der giver rummet farve hele aftenen.",
      usecase_en: "The big company party in a hired hall: enough bass for the dancefloor, and uplights that colour the room all evening.",
      parts: [
        { productId: "hojtaler_100", label_da: "Stor højtalerpakke", label_en: "Large speaker package", price: 1295 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
        { productId: "uplight_4", label_da: "Uplight 4-pak", label_en: "Uplight 4-pack", price: 595 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
      ],
    },
  },
  /* ── Arkets 5.2 Fredagsbaren ── */
  {
    id: "anl_fredagsbar_dansegulv",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Fredagsbar med dansegulv",
    name_en: "Friday Bar with a Dancefloor",
    desc_da: "Mellem højtalerpakke på stativer og en lysbar. Fredagsbaren der ender i dans.",
    desc_en: "The medium speaker package on stands with a light bar. The Friday bar that ends in dancing.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Til fredagsbaren på studiet eller arbejdspladsen, hvor musikken skal kunne skrues op, når baren lukker.",
      usecase_en: "For the Friday bar at university or work, where the music goes up once the bar closes.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
      ],
    },
  },
  {
    id: "anl_fredagsbar_deluxe",
    hidden: true,
    category: "lyd",
    image: "/images/product-hojtalerpakke-stor-white.webp",
    showPartImages: true,
    name_da: "Fredagsbar Deluxe",
    name_en: "Friday Bar Deluxe",
    desc_da: "Stor højtalerpakke, lysbar, fire uplights og en farvet lyskæde.",
    desc_en: "The large speaker package, a light bar, four uplights and coloured string lights.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Den fredagsbar der er vokset til en fest: lys på væggene, lyskæde over baren og bas nok til hele lokalet.",
      usecase_en: "The Friday bar that has grown into a party: light on the walls, string lights over the bar and bass for the whole room.",
      parts: [
        { productId: "hojtaler_100", label_da: "Stor højtalerpakke", label_en: "Large speaker package", price: 1295 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
        { productId: "uplight_4", label_da: "Uplight 4-pak", label_en: "Uplight 4-pack", price: 595 },
        { productId: "lyskaeder_farvet", label_da: "Lyskæde farvet", label_en: "Fairy lights coloured", price: 195 },
      ],
    },
  },
  /* ── Arkets 5.3 Bryllup ── */
  {
    id: "anl_bryllup_elegance",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Bryllup Elegance",
    name_en: "Wedding Elegance",
    desc_da: "Mellem højtalerpakke på stativer, discokugle 30 cm og mikrofon til talerne.",
    desc_en: "The medium speaker package on stands, a 30 cm mirror ball and a microphone for the speeches.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Det mindre bryllup hvor talerne skal høres ved bordene, og hvor discokuglen tændes til brudevalsen.",
      usecase_en: "The smaller wedding where the speeches must carry to the tables, and the mirror ball comes on for the first dance.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "discokugle_30", label_da: "Discokugle 30 cm", label_en: "Disco ball 30 cm", price: 545 },
        { productId: "mikrofon_kabel", label_da: "Håndholdt mikrofon (kabel)", label_en: "Handheld microphone (wired)", price: 95 },
      ],
    },
  },
  {
    id: "anl_bryllup_romance",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Bryllup Romance",
    name_en: "Wedding Romance",
    desc_da: "Mellem højtalerpakke, discokugle 40 cm, fire uplights og trådløs mikrofon.",
    desc_en: "The medium speaker package, a 40 cm mirror ball, four uplights and a wireless microphone.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Brylluppet hvor talerne holdes stående rundt om bordene, og hvor uplights varmer salen op, før dansen begynder.",
      usecase_en: "The wedding where speeches are made standing around the tables, and uplights warm the hall before the dancing starts.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "discokugle", label_da: "Discokugle 40 cm", label_en: "Disco ball 40 cm", price: 645 },
        { productId: "uplight_4", label_da: "Uplight 4-pak", label_en: "Uplight 4-pack", price: 595 },
        { productId: "mikrofon", label_da: "Trådløs mikrofon", label_en: "Wireless mic", price: 445 },
      ],
    },
  },
  {
    id: "anl_bryllup_grand",
    hidden: true,
    category: "lyd",
    image: "/images/product-hojtalerpakke-stor-white.webp",
    showPartImages: true,
    name_da: "Bryllup Grand",
    name_en: "Wedding Grand",
    desc_da: "Stor højtalerpakke, discokugle i guld, uplights, trådløs mikrofon og røggulv.",
    desc_en: "The large speaker package, a gold mirror ball, uplights, a wireless microphone and a low fog machine.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Det store bryllup: bas til dansegulvet, guldkugle over gulvet og et røggulv til brudevalsen.",
      usecase_en: "The big wedding: bass for the dancefloor, a gold ball above it and a fog floor for the first dance.",
      parts: [
        { productId: "hojtaler_100", label_da: "Stor højtalerpakke", label_en: "Large speaker package", price: 1295 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "discokugle_guld", label_da: "Discokugle 40 cm guld", label_en: "Disco ball 40 cm gold", price: 645 },
        { productId: "uplight_4", label_da: "Uplight 4-pak", label_en: "Uplight 4-pack", price: 595 },
        { productId: "mikrofon", label_da: "Trådløs mikrofon", label_en: "Wireless mic", price: 445 },
        { productId: "low_fog", label_da: "Low fog-maskine (røggulv)", label_en: "Low fog machine (fog floor)", price: 545 },
      ],
    },
  },
  {
    id: "anl_bryllup_dj",
    hidden: true,
    category: "lyd",
    image: "/images/product-hojtalerpakke-stor-white.webp",
    showPartImages: true,
    name_da: "Bryllup med DJ-pult",
    name_en: "Wedding with DJ Booth",
    desc_da: "Stor højtalerpakke, DJ-pult med klædt stativ, lysbar og fire uplights.",
    desc_en: "The large speaker package, a DJ booth with a draped stand, a light bar and four uplights.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Brylluppet hvor en ven eller en hyret DJ styrer musikken fra en rigtig pult, der også ser ud af noget.",
      usecase_en: "The wedding where a friend or a hired DJ runs the music from a real booth that also looks the part.",
      parts: [
        { productId: "hojtaler_100", label_da: "Stor højtalerpakke", label_en: "Large speaker package", price: 1295 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "dj_pult", label_da: "DJ-pult · AlphaTheta XDJ", label_en: "DJ system · AlphaTheta XDJ", price: 1695 },
        { productId: "dj_stativ", label_da: "DJ-stativ med klæde", label_en: "DJ stand with cloth", price: 395 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
        { productId: "uplight_4", label_da: "Uplight 4-pak", label_en: "Uplight 4-pack", price: 595 },
      ],
    },
  },
  /* ── Arkets 5.4 Fødselsdag ── */
  {
    id: "anl_foedselsdag",
    hidden: true,
    category: "lyd",
    image: "/images/product-party-v2-white.webp",
    showPartImages: true,
    name_da: "Fødselsdagsfest",
    name_en: "Birthday Party",
    desc_da: "Lille højtalerpakke og en lyseffekt. Musik og farve til fødselsdagen hjemme.",
    desc_en: "The small speaker package and one light effect. Music and colour for a birthday at home.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Fødselsdagen i lejligheden eller haven, hvor der skal spilles musik, uden at naboerne ringer.",
      usecase_en: "The birthday in the flat or the garden, with music that does not have the neighbours calling.",
      parts: [
        { productId: "party", label_da: "Lille højtalerpakke", label_en: "Small Speaker Package", price: 595 },
        { productId: "lyseffekt", label_da: "Enkelt lyseffekt", label_en: "Single light effect", price: 195 },
      ],
    },
  },
  {
    id: "anl_foedselsdag_rund",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Rund fødselsdag Deluxe",
    name_en: "Milestone Birthday Deluxe",
    desc_da: "Mellem højtalerpakke, lysbar og røgmaskine. Til de runde år med dansegulv.",
    desc_en: "The medium speaker package, a light bar and a fog machine. For a milestone birthday with a dancefloor.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "De 40, 50 eller 60 år, hvor der er lejet lokale, og hvor aftenen ender med dans.",
      usecase_en: "The 40th, 50th or 60th with a hired venue, where the evening ends in dancing.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
        { productId: "rog", label_da: "Røgmaskine", label_en: "Fog machine", price: 245 },
      ],
    },
  },
  {
    id: "anl_boernefoedselsdag",
    hidden: true,
    category: "lyd",
    image: "/images/product-thumpgo-v2-white.webp",
    showPartImages: true,
    name_da: "Børnefødselsdag",
    name_en: "Children's Birthday",
    desc_da: "Batterihøjtaler, lyseffekt og en sæbeboblemaskine med ekstra væske.",
    desc_en: "A battery speaker, a light effect and a bubble machine with extra fluid.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Børnefødselsdagen hvor musikken skal med ud i haven, og hvor sæbeboblerne er halvdelen af festen.",
      usecase_en: "The children's birthday where the music goes out into the garden, and the bubbles are half the party.",
      parts: [
        { productId: "thumpgo", label_da: "Mackie Thump GO", label_en: "Mackie Thump GO", price: 445 },
        { productId: "lyseffekt", label_da: "Enkelt lyseffekt", label_en: "Single light effect", price: 195 },
        { productId: "saebeboblemaskine", label_da: "Sæbeboblemaskine", label_en: "Bubble machine", price: 995 },
        { productId: "boblevaeske", label_da: "Ekstra boblevæske 5 liter", label_en: "Extra bubble fluid 5 litres", price: 295 },
      ],
    },
  },
  /* ── Arkets 5.5 Konfirmation ── */
  {
    id: "anl_konfirmation_telt",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Konfirmation i telt",
    name_en: "Confirmation in a Marquee",
    desc_da: "Mellem højtalerpakke på stativer, trådløs mikrofon og omformere til udendørsstik.",
    desc_en: "The medium speaker package on stands, a wireless microphone and adapters for outdoor sockets.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Konfirmationen i festteltet, hvor strømmen kommer fra huset, og hvor talerne skal høres i hele teltet.",
      usecase_en: "The confirmation in a marquee, where the power comes from the house and the speeches must carry through the tent.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "mikrofon", label_da: "Trådløs mikrofon", label_en: "Wireless mic", price: 445 },
        { productId: "omformer_udendors", label_da: "Omformer til udendørs stik", label_en: "Adapter for outdoor sockets", price: 30, qty: 3 },
      ],
    },
  },
  {
    id: "anl_konfirmation_inde",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Konfirmation indendørs",
    name_en: "Confirmation Indoors",
    desc_da: "Mellem højtalerpakke på stativer og en trådløs mikrofon til talerne.",
    desc_en: "The medium speaker package on stands and a wireless microphone for the speeches.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Konfirmationen i forsamlingshuset eller derhjemme, hvor talerne er det vigtigste, og musikken kommer bagefter.",
      usecase_en: "The confirmation in a village hall or at home, where the speeches matter most and the music comes after.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "mikrofon", label_da: "Trådløs mikrofon", label_en: "Wireless mic", price: 445 },
      ],
    },
  },
  {
    id: "anl_konfirmation_elegance",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Konfirmation Elegance",
    name_en: "Confirmation Elegance",
    desc_da: "Mellem højtalerpakke, trådløs mikrofon, fire uplights og omformere til udendørsstik.",
    desc_en: "The medium speaker package, a wireless microphone, four uplights and adapters for outdoor sockets.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Konfirmationen hvor teltet eller salen skal se festligt ud, og hvor uplights gør arbejdet, når det bliver mørkt.",
      usecase_en: "The confirmation where the marquee or hall should look festive, and uplights do the work once it gets dark.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "mikrofon", label_da: "Trådløs mikrofon", label_en: "Wireless mic", price: 445 },
        { productId: "uplight_4", label_da: "Uplight 4-pak", label_en: "Uplight 4-pack", price: 595 },
        { productId: "omformer_udendors", label_da: "Omformer til udendørs stik", label_en: "Adapter for outdoor sockets", price: 30, qty: 3 },
      ],
    },
  },
  /* ── Arkets 5.6 Studenterfest ── */
  {
    id: "anl_sidste_stop",
    hidden: true,
    category: "lyd",
    image: "/images/product-hojtalerpakke-stor-white.webp",
    showPartImages: true,
    name_da: "Sidste stop",
    name_en: "Last Stop",
    desc_da: "Stor højtalerpakke på stativer og to lysbarer. Til studenterfesten i salen.",
    desc_en: "The large speaker package on stands and two light bars. For the graduation party in the hall.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Den sidste fest efter studenterkørslen: bas nok til 50-100 gæster og lys fra begge ender af dansegulvet.",
      usecase_en: "The last party after the graduation truck: bass for 50-100 guests and light from both ends of the dancefloor.",
      parts: [
        { productId: "hojtaler_100", label_da: "Stor højtalerpakke", label_en: "Large speaker package", price: 1295 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 790, qty: 2 },
      ],
    },
  },
  {
    id: "anl_sidste_skoledag",
    hidden: true,
    category: "lyd",
    image: "/images/product-soundboks-v2-white.webp",
    showPartImages: true,
    name_da: "Sidste skoledag",
    name_en: "Last Day of School",
    desc_da: "Soundboks 4 og en snemaskine med ekstra væske. Ingen strøm nødvendig.",
    desc_en: "A Soundboks 4 and a snow machine with extra fluid. No power needed.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Sidste skoledag i skolegården, hvor musikken skal kunne høres udendørs, og sneen laver billederne.",
      usecase_en: "The last day of school in the yard, where the music has to carry outdoors and the snow makes the photos.",
      parts: [
        { productId: "soundboks", label_da: "Soundboks 4", label_en: "Soundboks 4", price: 695 },
        { productId: "snemaskine", label_da: "Snemaskine", label_en: "Snow machine", price: 445 },
        { productId: "snevaeske", label_da: "Ekstra snevæske 5 liter", label_en: "Extra snow fluid 5 litres", price: 295 },
      ],
    },
  },
  {
    id: "anl_translokation",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Translokationsfest",
    name_en: "Graduation Ceremony Party",
    desc_da: "Mellem højtalerpakke på stativer, lysbar og stroboskop med styring.",
    desc_en: "The medium speaker package on stands, a light bar and a strobe with a controller.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Festen efter translokationen, hvor dagen begynder pænt og slutter på dansegulvet.",
      usecase_en: "The party after the ceremony, where the day starts formal and ends on the dancefloor.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
        { productId: "stroboskop", label_da: "Stroboskop med styring", label_en: "Strobe light with controller", price: 395 },
      ],
    },
  },
  /* ── Arkets 5.7 Polterabend ── */
  {
    id: "anl_polterabend_hende",
    hidden: true,
    category: "lyd",
    image: "/images/product-soundboks-v2-white.webp",
    showPartImages: true,
    name_da: "Polterabend med lys og røg",
    name_en: "Hen Party with Light and Fog",
    desc_da: "Soundboks 4, lysbar og røgmaskine. Batteridrevet lyd, lys der skal bruge strøm.",
    desc_en: "A Soundboks 4, a light bar and a fog machine. Battery-powered sound, mains-powered light.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Polterabenden der starter ude og ender inde: højtaleren kan tages med, lys og røg venter hjemme.",
      usecase_en: "The hen party that starts outside and ends indoors: the speaker comes along, light and fog wait at home.",
      parts: [
        { productId: "soundboks", label_da: "Soundboks 4", label_en: "Soundboks 4", price: 695 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
        { productId: "rog", label_da: "Røgmaskine", label_en: "Fog machine", price: 245 },
      ],
    },
  },
  {
    id: "anl_polterabend_ham",
    hidden: true,
    category: "lyd",
    image: "/images/product-soundboks-v2-white.webp",
    showPartImages: true,
    name_da: "Polterabend med bas",
    name_en: "Stag Party with Bass",
    desc_da: "Soundboks 4, røgmaskine og lysbar. Til polterabenden der skal kunne høres.",
    desc_en: "A Soundboks 4, a fog machine and a light bar. For the stag party that needs to be heard.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Polterabenden i sommerhuset eller kælderen, hvor der skal være tryk på fra første sang.",
      usecase_en: "The stag party in a summer house or basement, where it has to hit hard from the first song.",
      parts: [
        { productId: "soundboks", label_da: "Soundboks 4", label_en: "Soundboks 4", price: 695 },
        { productId: "rog", label_da: "Røgmaskine", label_en: "Fog machine", price: 245 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
      ],
    },
  },
  /* ── Arkets 5.8 Reception & Jubilæum ── */
  {
    id: "anl_jubilaeum",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Jubilæumsfest",
    name_en: "Anniversary Party",
    desc_da: "Mellem højtalerpakke på stativer og en trådløs mikrofon til talerne.",
    desc_en: "The medium speaker package on stands and a wireless microphone for the speeches.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Jubilæet hvor der skal holdes tale for en, der ikke selv vil stå stille, og spilles musik bagefter.",
      usecase_en: "The anniversary with a speech for someone who will not stand still, and music afterwards.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "mikrofon", label_da: "Trådløs mikrofon", label_en: "Wireless mic", price: 445 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
      ],
    },
  },
  {
    id: "anl_aabent_hus",
    hidden: true,
    category: "lyd",
    image: "/images/product-soundboks-v2-white.webp",
    showPartImages: true,
    name_da: "Åbent hus",
    name_en: "Open House",
    desc_da: "Soundboks 4 og fire uplights. Baggrundsmusik og farve på væggene.",
    desc_en: "A Soundboks 4 and four uplights. Background music and colour on the walls.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Åbent hus hvor musikken skal være til stede uden at fylde, og hvor lokalet skal se indbydende ud.",
      usecase_en: "An open house where the music should be present without taking over, and the room should look inviting.",
      parts: [
        { productId: "soundboks", label_da: "Soundboks 4", label_en: "Soundboks 4", price: 695 },
        { productId: "uplight_4", label_da: "Uplight 4-pak", label_en: "Uplight 4-pack", price: 595 },
      ],
    },
  },
  /* ── Arkets 5.9 Teambuilding & Personaledag ── */
  {
    id: "anl_sommerfest",
    hidden: true,
    category: "lyd",
    image: "/images/product-party-v2-white.webp",
    showPartImages: true,
    name_da: "Sommerfest",
    name_en: "Summer Party",
    desc_da: "Lille højtalerpakke på stativer, lysbar og discokugle 30 cm.",
    desc_en: "The small speaker package on stands, a light bar and a 30 cm mirror ball.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Personalets sommerfest, hvor der spises først og danses bagefter, og hvor discokuglen markerer skiftet.",
      usecase_en: "The staff summer party, where you eat first and dance after, and the mirror ball marks the change.",
      parts: [
        { productId: "party", label_da: "Lille højtalerpakke", label_en: "Small Speaker Package", price: 595 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
        { productId: "discokugle_30", label_da: "Discokugle 30 cm", label_en: "Disco ball 30 cm", price: 545 },
      ],
    },
  },
  /* ── Arkets 5.10 Foreningsfest/Klubfest ── */
  {
    id: "anl_klubfest",
    hidden: true,
    category: "lyd",
    image: "/images/product-hojtalerpakke-stor-white.webp",
    showPartImages: true,
    name_da: "Klubfest",
    name_en: "Club Party",
    desc_da: "Stor højtalerpakke, to lyseffekter og en mikrofon til præmieoverrækkelsen.",
    desc_en: "The large speaker package, two light effects and a microphone for the prize-giving.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Klubbens fest i hallen eller klubhuset: højt nok til 50-100, og en mikrofon når pokalerne skal deles ud.",
      usecase_en: "The club party in the hall or clubhouse: loud enough for 50-100, and a microphone when the cups are handed out.",
      parts: [
        { productId: "hojtaler_100", label_da: "Stor højtalerpakke", label_en: "Large speaker package", price: 1295 },
        { productId: "lyseffekt", label_da: "Enkelt lyseffekt", label_en: "Single light effect", price: 390, qty: 2 },
        { productId: "mikrofon_kabel", label_da: "Håndholdt mikrofon (kabel)", label_en: "Handheld microphone (wired)", price: 95 },
      ],
    },
  },
  {
    id: "anl_turneringsfest",
    hidden: true,
    category: "lyd",
    image: "/images/product-soundboks-v2-white.webp",
    showPartImages: true,
    name_da: "Turneringsfest",
    name_en: "Tournament Party",
    desc_da: "To Soundboks 4 og et ekstra batteri. Lyd hele dagen, uden en stikkontakt.",
    desc_en: "Two Soundboks 4 and a spare battery. Sound all day, without a socket.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Turneringen udenfor, hvor lyden skal dække to baner og holde fra opvarmning til præmier.",
      usecase_en: "The tournament outdoors, where the sound must cover two pitches and last from warm-up to prizes.",
      parts: [
        { productId: "soundboks", label_da: "Soundboks 4", label_en: "Soundboks 4", price: 1390, qty: 2 },
        { productId: "batteri", label_da: "Soundboks batteri", label_en: "Soundboks battery", price: 395 },
      ],
    },
  },
  /* ── Arkets 5.11 Havefest & Grillfest ── */
  {
    id: "anl_havefest",
    hidden: true,
    category: "lyd",
    image: "/images/product-thumpgo-v2-white.webp",
    showPartImages: true,
    name_da: "Havefest",
    name_en: "Garden Party",
    desc_da: "Batterihøjtaler og to farvede lyskæder. Ingen strøm nødvendig til lyden.",
    desc_en: "A battery speaker and two sets of coloured string lights. No power needed for the sound.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Havefesten hvor lyskæderne hænges op mellem træerne, og højtaleren kan stå, hvor der ikke er et stik.",
      usecase_en: "The garden party with string lights between the trees and a speaker that stands where there is no socket.",
      parts: [
        { productId: "thumpgo", label_da: "Mackie Thump GO", label_en: "Mackie Thump GO", price: 445 },
        { productId: "lyskaeder_farvet", label_da: "Lyskæde farvet", label_en: "Fairy lights coloured", price: 390, qty: 2 },
      ],
    },
  },
  {
    id: "anl_grillaften",
    hidden: true,
    category: "lyd",
    image: "/images/product-thumpgo-v2-white.webp",
    showPartImages: true,
    name_da: "Grillaften",
    name_en: "Barbecue Evening",
    desc_da: "Batterihøjtaler og to hvide lyskæder. Varmt lys og musik i baggrunden.",
    desc_en: "A battery speaker and two sets of warm white string lights. Warm light and music in the background.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Grillaftenen hvor musikken skal være lav nok til at snakke over, og lyset varmt nok til at blive siddende.",
      usecase_en: "The barbecue where the music stays low enough to talk over, and the light warm enough to stay out.",
      parts: [
        { productId: "thumpgo", label_da: "Mackie Thump GO", label_en: "Mackie Thump GO", price: 445 },
        { productId: "lyskaeder", label_da: "Lyskæde varm hvid", label_en: "Fairy lights warm white", price: 390, qty: 2 },
      ],
    },
  },
  {
    id: "anl_terrassefest",
    hidden: true,
    category: "lyd",
    image: "/images/product-soundboks-v2-white.webp",
    showPartImages: true,
    name_da: "Terrassefest",
    name_en: "Terrace Party",
    desc_da: "Soundboks 4 og to farvede lyskæder. Til terrassen hvor der skal danses.",
    desc_en: "A Soundboks 4 and two sets of coloured string lights. For the terrace where there will be dancing.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Terrassefesten hvor højtaleren skal kunne følge med udenfor, og lyskæderne markerer, hvor festen er.",
      usecase_en: "The terrace party where the speaker comes outside, and the string lights mark where the party is.",
      parts: [
        { productId: "soundboks", label_da: "Soundboks 4", label_en: "Soundboks 4", price: 695 },
        { productId: "lyskaeder_farvet", label_da: "Lyskæde farvet", label_en: "Fairy lights coloured", price: 390, qty: 2 },
      ],
    },
  },
  {
    id: "anl_gaardfest",
    hidden: true,
    category: "lyd",
    image: "/images/product-soundboks-v2-white.webp",
    showPartImages: true,
    name_da: "Gårdfest",
    name_en: "Courtyard Party",
    desc_da: "Soundboks 4 og to hvide lyskæder. Batteridrevet lyd til baggården.",
    desc_en: "A Soundboks 4 and two sets of warm white string lights. Battery sound for the courtyard.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Gårdfesten i baggården, hvor der ikke er et stik, og hvor lyskæderne gør gården til et sted.",
      usecase_en: "The courtyard party where there is no socket, and the string lights turn the yard into a place.",
      parts: [
        { productId: "soundboks", label_da: "Soundboks 4", label_en: "Soundboks 4", price: 695 },
        { productId: "lyskaeder", label_da: "Lyskæde varm hvid", label_en: "Fairy lights warm white", price: 390, qty: 2 },
      ],
    },
  },
  /* ── Arkets 5.12 Poolparty ── */
  {
    id: "anl_poolparty",
    hidden: true,
    category: "lyd",
    image: "/images/product-soundboks-v2-white.webp",
    showPartImages: true,
    name_da: "Poolparty",
    name_en: "Pool Party",
    desc_da: "Soundboks 4, røgmaskine og RGB-laser. Batteridrevet lyd tæt på vandet.",
    desc_en: "A Soundboks 4, a fog machine and an RGB laser. Battery sound near the water.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Poolfesten hvor højtaleren skal kunne stå uden kabel til vandet, og laseren først bliver til noget i røgen.",
      usecase_en: "The pool party where the speaker stands without a cable to the water, and the laser only shows in the fog.",
      parts: [
        { productId: "soundboks", label_da: "Soundboks 4", label_en: "Soundboks 4", price: 695 },
        { productId: "rog", label_da: "Røgmaskine", label_en: "Fog machine", price: 245 },
        { productId: "laser", label_da: "RGB-laser", label_en: "RGB laser", price: 595 },
      ],
    },
  },
  {
    id: "anl_poolparty_deluxe",
    hidden: true,
    category: "lyd",
    image: "/images/product-soundboks-v2-white.webp",
    showPartImages: true,
    name_da: "Poolparty Deluxe",
    name_en: "Pool Party Deluxe",
    desc_da: "To Soundboks 4, røgmaskine og to RGB-lasere. Lyd og lys i begge ender.",
    desc_en: "Two Soundboks 4, a fog machine and two RGB lasers. Sound and light at both ends.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Den store poolfest, hvor lyden skal nå hele vejen rundt, og lyset kommer fra to sider.",
      usecase_en: "The big pool party, where the sound has to reach all the way round and the light comes from two sides.",
      parts: [
        { productId: "soundboks", label_da: "Soundboks 4", label_en: "Soundboks 4", price: 1390, qty: 2 },
        { productId: "rog", label_da: "Røgmaskine", label_en: "Fog machine", price: 245 },
        { productId: "laser", label_da: "RGB-laser", label_en: "RGB laser", price: 1190, qty: 2 },
      ],
    },
  },
  /* ── Arkets 5.13 Discofest ── */
  {
    id: "anl_disco_light",
    hidden: true,
    category: "lyd",
    image: "/images/product-party-v2-white.webp",
    showPartImages: true,
    name_da: "Diskofest light",
    name_en: "Disco Night Light",
    desc_da: "Lille højtalerpakke, discokugle 30 cm og fire uplights.",
    desc_en: "The small speaker package, a 30 cm mirror ball and four uplights.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Diskofesten i stuen eller kælderen, hvor kuglen og uplights laver hele stemningen.",
      usecase_en: "The disco night in the living room or basement, where the ball and the uplights make the whole mood.",
      parts: [
        { productId: "party", label_da: "Lille højtalerpakke", label_en: "Small Speaker Package", price: 595 },
        { productId: "discokugle_30", label_da: "Discokugle 30 cm", label_en: "Disco ball 30 cm", price: 545 },
        { productId: "uplight_4", label_da: "Uplight 4-pak", label_en: "Uplight 4-pack", price: 595 },
      ],
    },
  },
  {
    id: "anl_disco_deluxe",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Diskokuglen Deluxe",
    name_en: "Mirror Ball Deluxe",
    desc_da: "Mellem højtalerpakke, discokugle 40 cm og fire uplights.",
    desc_en: "The medium speaker package, a 40 cm mirror ball and four uplights.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Diskofesten i lejet lokale: større kugle, mere lyd og farve på væggene hele aftenen.",
      usecase_en: "The disco night in a hired room: a bigger ball, more sound and colour on the walls all evening.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "discokugle", label_da: "Discokugle 40 cm", label_en: "Disco ball 40 cm", price: 645 },
        { productId: "uplight_4", label_da: "Uplight 4-pak", label_en: "Uplight 4-pack", price: 595 },
      ],
    },
  },
  {
    id: "anl_glitterballet",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Glitterballet",
    name_en: "The Gold Ball",
    desc_da: "Mellem højtalerpakke, discokugle 40 cm i guld og fire uplights.",
    desc_en: "The medium speaker package, a 40 cm gold mirror ball and four uplights.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Festen hvor guldkuglen er midtpunktet: varmere lys end den sølvfarvede, og uplights i samme tone.",
      usecase_en: "The party where the gold ball is the centrepiece: warmer light than the silver one, with uplights to match.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "discokugle_guld", label_da: "Discokugle 40 cm guld", label_en: "Disco ball 40 cm gold", price: 645 },
        { productId: "uplight_4", label_da: "Uplight 4-pak", label_en: "Uplight 4-pack", price: 595 },
      ],
    },
  },
  /* ── Arkets 5.14 Ungdomsfest ── */
  {
    id: "anl_ungdomsfest_light",
    hidden: true,
    category: "lyd",
    image: "/images/product-soundboks-v2-white.webp",
    showPartImages: true,
    name_da: "Ungdomsfest light",
    name_en: "Teen Party Light",
    desc_da: "Soundboks 4, RGB-laser, røgmaskine og lysbar.",
    desc_en: "A Soundboks 4, an RGB laser, a fog machine and a light bar.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Ungdomsfesten hjemme eller i klubben, hvor laseren og røgen betyder mere end antallet af watt.",
      usecase_en: "The teen party at home or at the club, where the laser and the fog matter more than the watts.",
      parts: [
        { productId: "soundboks", label_da: "Soundboks 4", label_en: "Soundboks 4", price: 695 },
        { productId: "laser", label_da: "RGB-laser", label_en: "RGB laser", price: 595 },
        { productId: "rog", label_da: "Røgmaskine", label_en: "Fog machine", price: 245 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
      ],
    },
  },
  {
    id: "anl_ungdomsfest_stor",
    hidden: true,
    category: "lyd",
    image: "/images/product-hojtalerpakke-stor-white.webp",
    showPartImages: true,
    name_da: "Ungdomsfest stor",
    name_en: "Teen Party Large",
    desc_da: "Stor højtalerpakke, RGB-laser, røg, lysbar, stroboskop og UV-lampe.",
    desc_en: "The large speaker package, an RGB laser, fog, a light bar, a strobe and a UV light.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Den store ungdomsfest i en sal: alt lyset på én gang, og bas nok til at gulvet mærker det.",
      usecase_en: "The big teen party in a hall: every light at once, and enough bass for the floor to feel it.",
      parts: [
        { productId: "hojtaler_100", label_da: "Stor højtalerpakke", label_en: "Large speaker package", price: 1295 },
        { productId: "laser", label_da: "RGB-laser", label_en: "RGB laser", price: 595 },
        { productId: "rog", label_da: "Røgmaskine", label_en: "Fog machine", price: 245 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
        { productId: "stroboskop", label_da: "Stroboskop med styring", label_en: "Strobe light with controller", price: 395 },
        { productId: "uv_lampe", label_da: "UV-lampe", label_en: "UV light", price: 245 },
      ],
    },
  },
  /* ── Arkets 6.1 Nytårsfest ── */
  {
    id: "anl_nytaar_lille",
    hidden: true,
    category: "lyd",
    image: "/images/product-thumpgo-v2-white.webp",
    showPartImages: true,
    name_da: "Nytår i lejligheden",
    name_en: "New Year at Home",
    desc_da: "Batterihøjtaler, RGB-laser og en lyseffekt. Plads i en lejlighed.",
    desc_en: "A battery speaker, an RGB laser and a light effect. Fits in a flat.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Nytårsaften hjemme, hvor der ikke er plads til stativer, men hvor der stadig skal danses efter midnat.",
      usecase_en: "New Year's Eve at home, with no room for stands, but still dancing after midnight.",
      parts: [
        { productId: "thumpgo", label_da: "Mackie Thump GO", label_en: "Mackie Thump GO", price: 445 },
        { productId: "laser", label_da: "RGB-laser", label_en: "RGB laser", price: 595 },
        { productId: "lyseffekt", label_da: "Enkelt lyseffekt", label_en: "Single light effect", price: 195 },
      ],
    },
  },
  {
    id: "anl_nytaar_stor",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Stor nytårsfest",
    name_en: "New Year's Party",
    desc_da: "Mellem højtalerpakke, lysbar, røgmaskine og UV-lampe.",
    desc_en: "The medium speaker package, a light bar, a fog machine and a UV light.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Nytårsfesten i lejet lokale, hvor aftenen skal holde fra middagen til langt over midnat.",
      usecase_en: "The New Year's party in a hired room, where the evening runs from dinner until long past midnight.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
        { productId: "rog", label_da: "Røgmaskine", label_en: "Fog machine", price: 245 },
        { productId: "uv_lampe", label_da: "UV-lampe", label_en: "UV light", price: 245 },
      ],
    },
  },
  /* ── Arkets 6.2 Julefrokost ── */
  {
    id: "anl_julefrokost_lille",
    hidden: true,
    category: "lyd",
    image: "/images/product-thumpgo-v2-white.webp",
    showPartImages: true,
    name_da: "Den lille julefrokost",
    name_en: "The Small Christmas Lunch",
    desc_da: "Batterihøjtaler og en lyseffekt. Til julefrokosten på kontoret eller hjemme.",
    desc_en: "A battery speaker and one light effect. For the Christmas lunch at the office or at home.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Julefrokosten for en afdeling eller en familie, hvor musikken skal kunne skrues op sidst på eftermiddagen.",
      usecase_en: "The Christmas lunch for a department or a family, where the music goes up late in the afternoon.",
      parts: [
        { productId: "thumpgo", label_da: "Mackie Thump GO", label_en: "Mackie Thump GO", price: 445 },
        { productId: "lyseffekt", label_da: "Enkelt lyseffekt", label_en: "Single light effect", price: 195 },
      ],
    },
  },
  {
    id: "anl_julefrokost_firma",
    hidden: true,
    category: "lyd",
    image: "/images/product-festival-v2-white.webp",
    showPartImages: true,
    name_da: "Firma julefrokost",
    name_en: "Company Christmas Lunch",
    desc_da: "Mellem højtalerpakke på stativer, lysbar og mikrofon til talen.",
    desc_en: "The medium speaker package on stands, a light bar and a microphone for the speech.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Julefrokosten hvor chefen skal sige noget først, og hvor der danses, når bordene er ryddet.",
      usecase_en: "The Christmas lunch where the boss speaks first, and there is dancing once the tables are cleared.",
      parts: [
        { productId: "festival", label_da: "Mellem højtalerpakke", label_en: "Medium Speaker Package", price: 795 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "mikrofon_kabel", label_da: "Håndholdt mikrofon (kabel)", label_en: "Handheld microphone (wired)", price: 95 },
      ],
    },
  },
  {
    id: "anl_julefrokost_dj",
    hidden: true,
    category: "lyd",
    image: "/images/product-hojtalerpakke-stor-white.webp",
    showPartImages: true,
    name_da: "Firma julefrokost med DJ-pult",
    name_en: "Company Christmas Lunch with DJ Booth",
    desc_da: "Stor højtalerpakke, DJ-pult med klædt stativ og lysbar.",
    desc_en: "The large speaker package, a DJ booth with a draped stand and a light bar.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Den store julefrokost, hvor en kollega eller en hyret DJ overtager musikken efter maden.",
      usecase_en: "The big Christmas lunch, where a colleague or a hired DJ takes over the music after dinner.",
      parts: [
        { productId: "hojtaler_100", label_da: "Stor højtalerpakke", label_en: "Large speaker package", price: 1295 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
        { productId: "dj_pult", label_da: "DJ-pult · AlphaTheta XDJ", label_en: "DJ system · AlphaTheta XDJ", price: 1695 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
        { productId: "dj_stativ", label_da: "DJ-stativ med klæde", label_en: "DJ stand with cloth", price: 395 },
      ],
    },
  },
  /* ── Arkets 6.3 Fastalavn ── */
  {
    id: "anl_fastelavn_dronning",
    hidden: true,
    category: "lyd",
    image: "/images/product-thumpgo-v2-white.webp",
    showPartImages: true,
    name_da: "Fastelavn med sæbebobler",
    name_en: "Shrovetide with Bubbles",
    desc_da: "Batterihøjtaler og en sæbeboblemaskine. Ingen strøm nødvendig til lyden.",
    desc_en: "A battery speaker and a bubble machine. No power needed for the sound.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Fastelavn i gården eller foreningen, hvor boblerne holder de mindste beskæftiget mellem tøndeslagene.",
      usecase_en: "Shrovetide in the yard or the club, where the bubbles keep the little ones busy between rounds.",
      parts: [
        { productId: "thumpgo", label_da: "Mackie Thump GO", label_en: "Mackie Thump GO", price: 445 },
        { productId: "saebeboblemaskine", label_da: "Sæbeboblemaskine", label_en: "Bubble machine", price: 995 },
      ],
    },
  },
  {
    id: "anl_fastelavn_konge",
    hidden: true,
    category: "lyd",
    image: "/images/product-thumpgo-v2-white.webp",
    showPartImages: true,
    name_da: "Fastelavn med lys og bobler",
    name_en: "Shrovetide with Light and Bubbles",
    desc_da: "Batterihøjtaler, sæbeboblemaskine og en lyseffekt.",
    desc_en: "A battery speaker, a bubble machine and a light effect.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Fastelavnsfesten der fortsætter indenfor, når tønden er slået ned, og der skal være fest bagefter.",
      usecase_en: "The Shrovetide party that carries on indoors once the barrel is down, and the party continues.",
      parts: [
        { productId: "thumpgo", label_da: "Mackie Thump GO", label_en: "Mackie Thump GO", price: 445 },
        { productId: "saebeboblemaskine", label_da: "Sæbeboblemaskine", label_en: "Bubble machine", price: 995 },
        { productId: "lyseffekt", label_da: "Enkelt lyseffekt", label_en: "Single light effect", price: 195 },
      ],
    },
  },
  /* ── Arkets 6.4 Sommer ── */
  {
    id: "anl_sankthans",
    hidden: true,
    category: "lyd",
    image: "/images/product-thumpgo-v2-white.webp",
    showPartImages: true,
    name_da: "Sankt Hans",
    name_en: "Midsummer Eve",
    desc_da: "Batterihøjtaler og en hvid lyskæde. Til aftenen ved bålet.",
    desc_en: "A battery speaker and warm white string lights. For the evening by the bonfire.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Sankt Hans på stranden eller i haven, hvor der ikke er strøm, og hvor båltalen skal kunne høres.",
      usecase_en: "Midsummer Eve on the beach or in the garden, with no power, where the bonfire speech must be heard.",
      parts: [
        { productId: "thumpgo", label_da: "Mackie Thump GO", label_en: "Mackie Thump GO", price: 445 },
        { productId: "lyskaeder", label_da: "Lyskæde varm hvid", label_en: "Fairy lights warm white", price: 195 },
      ],
    },
  },
  {
    id: "anl_firma_sommerfest",
    hidden: true,
    category: "lyd",
    image: "/images/product-soundboks-v2-white.webp",
    showPartImages: true,
    name_da: "Firma sommerfest",
    name_en: "Company Summer Party",
    desc_da: "Soundboks 4, to hvide lyskæder og en lysbar. Ude om dagen, dans om aftenen.",
    desc_en: "A Soundboks 4, two sets of warm white string lights and a light bar. Outdoors by day, dancing by night.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Firmaets sommerfest, der begynder udenfor i dagslys og ender indenfor, når lysbaren tændes.",
      usecase_en: "The company summer party that starts outdoors in daylight and ends inside when the light bar comes on.",
      parts: [
        { productId: "soundboks", label_da: "Soundboks 4", label_en: "Soundboks 4", price: 695 },
        { productId: "lyskaeder", label_da: "Lyskæde varm hvid", label_en: "Fairy lights warm white", price: 390, qty: 2 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
      ],
    },
  },
  /* ── Arkets 6.6 Halloween ── */
  {
    id: "anl_halloween_stor_sal",
    hidden: true,
    category: "lyd",
    image: "/images/product-hojtalerpakke-stor-white.webp",
    showPartImages: true,
    name_da: "Halloween i salen",
    name_en: "Halloween in the Hall",
    desc_da: "Stor højtalerpakke på stativer, lysbar og røgmaskine.",
    desc_en: "The large speaker package on stands, a light bar and a fog machine.",
    allowedAddons: [...KOERSEL],
    bundle: {
      usecase_da: "Halloweenfesten i en lejet sal, hvor røgen fylder gulvet, og bassen bærer til bagerste væg.",
      usecase_en: "The Halloween party in a hired hall, where the fog fills the floor and the bass reaches the back wall.",
      parts: [
        { productId: "hojtaler_100", label_da: "Stor højtalerpakke", label_en: "Large speaker package", price: 1295 },
        { productId: "lys", label_da: "Lysbar", label_en: "Light bar", price: 395 },
        { productId: "rog", label_da: "Røgmaskine", label_en: "Fog machine", price: 245 },
        { productId: "stativer", label_da: "Højtalerstativer", label_en: "Speaker stands", price: 95 },
      ],
    },
  },
];

/** Id'erne, så de kan sættes i AFVENTER_FOTO og tændes samlet. */
export const ANLEDNING_PAKKE_IDS: string[] = anledningPakker.map((p) => p.id);
