import type { Locale } from "@/lib/i18n";

/**
 * Pakkelisten på engelsk.
 *
 * `contents` findes kun på dansk i kataloget, og listen bruges to steder på
 * de engelske sider: hover-panelet på produktkortene (CategoryProductGrid) og
 * svaret på "What is included when I rent …" (productFaq.ts). Begge steder
 * stod der dansk midt i en engelsk sætning, "Wireless microphone comes with
 * Trådløs håndholdt mic, Modtager og Kabelforbindelse til højtaler".
 *
 * Løsningen er en ORDBOG og ikke et `contents_en`-felt på hvert produkt, af
 * to grunde:
 *
 *  1. Kataloget kan overskrives fra /admin og bor i KV. Et nyt felt i
 *     products.ts ville aldrig nå frem på en installation, hvor KV allerede
 *     har et katalog, se mergeRentals i useProducts.ts, der netop findes
 *     for at lappe den slags huller.
 *  2. Ordforrådet er lille og gentager sig selv: "Strømkabel" står i tolv
 *     pakker. Oversat ét sted kan de tolv ikke drive fra hinanden.
 *
 * Ord, der ikke står her, falder tilbage til dansk. Det er med vilje, en
 * teknisk delnavn på dansk er bedre end ingen linje, men
 * pakkeliste-engelsk.test.ts fejler, hvis et produkt i products.ts bruger et
 * ord, ordbogen ikke kender, så nye produkter ikke stille og roligt gør
 * listen dansk igen.
 */
export const CONTENTS_EN: Record<string, string> = {
  "Pioneer DDJ-FLX4": "Pioneer DDJ-FLX4",
  "iPad i flightcase": "iPad in flight case",
  "DJ-hovedtelefoner · Fun Generation HP 5": "DJ headphones · Fun Generation HP 5",
  "Fun Generation HP 5": "Fun Generation HP 5",
  "3 m kabel": "3 m cable",
  "6,3 mm jack-adapter": "6.3 mm jack adapter",
  "Tilslutningskabler": "Connection cables",
  "DJ-pult · Pioneer DDJ-FLX4": "DJ controller · Pioneer DDJ-FLX4",
  "Subwoofer 12”": "Subwoofer 12 inch",
  "DJ/musikafvikler": "DJ/music host",
  "DJ-pult": "DJ booth",
  "Minimum 3 timer": "Minimum 3 hours",
  "Mackie Thump GO": "Mackie Thump GO",
  "Lille højtalerpakke": "Small Speaker Package",
  "Mellem højtalerpakke": "Medium Speaker Package",
  "Stor højtalerpakke": "Large speaker package",
  "Stroboskop": "Strobe light",
  "Stroboskop med styring": "Strobe light with controller",
  "Soundboks batteri": "Soundboks battery",
  "Enkelt lyseffekt": "Single light effect",
  "Bæretaske": "Carry bag",
  "Levering + opsætning": "Delivery + setup",
  "Afhentning efter festen": "Collection after the party",
  "Levering + afhentning (begge veje)": "Delivery + collection (both ways)",
  "Mixer lille · Mackie Mix12FX": "Small mixer · Mackie Mix12FX",
  "Mixer med effekter · t.mix 1202 FXMP USB": "Mixer with effects · t.mix 1202 FXMP USB",
  "Mixer stor · t.mix 1402 FXMP USB": "Large mixer · t.mix 1402 FXMP USB",
  "Lydmand": "Sound engineer",
  "Faktureringsgebyr": "Invoicing fee",
  "Batteripakke til tale": "Battery-powered speech package",
  "Trådløs talepakke": "Wireless speech package",
  "To trådløse mikrofoner og lyd": "Two wireless microphones and PA",
  "AV-pakke med to trådløse mikrofoner": "AV package with two wireless microphones",
  "Heksetimen": "The Witching Hour",
  "Monsterfesten": "Monster Party",
  "Midnatsklubben": "The Midnight Club",
  "Festpakke med lydmand": "Party package with sound engineer",
  "Firmaevent med lydmand": "Corporate event with sound engineer",
  "Stor fest med lydmand": "Big party with sound engineer",
  "Festpakke 0-30": "Party package 0-30",
  "Festpakke 30-50": "Party package 30-50",
  "Festpakke 50-100": "Party package 50-100",
  "Elegant festpakke": "Elegant party package",
  "Festpakke 150": "Party package 150",
  "Festpakke 250": "Party package 250",
  "Bryllupspakke": "Wedding package",
  "Firmafestpakke": "Company party package",
  "Udendørspakke": "Outdoor package",
  "Studenterpakken": "Graduation package",
  "Filmaften-pakken": "Movie night package",
  "Stemningslys-pakken": "Ambient light package",
  "Diskolys-pakken": "Disco light package",
  "Teenagefest-lys": "Teen party lights",
  "Festtelt-lys": "Party tent lights",
  "Bryllupslys-pakken": "Wedding light package",
  "Diskotek-pakken": "Club light package",
  "Stor soundboks pakke": "Large Soundboks package",
  "Lille soundboks pakke": "Small Soundboks package",
  "Ungdomsfest-pakken": "Youth party package",
  "Stor ungdomsfest-pakke": "Large youth party package",
  "Speakerpakke 0-30": "Speaker package 0-30",
  "Speakerpakke 30-50": "Speaker package 30-50",
  "Speakerpakke trådløs 0-30": "Wireless speaker package 0-30",
  "Festlys 0-50": "Party lights 0-50",
  "Festlys 50-100": "Party lights 50-100",
  "Lysshow": "Light show",
  "Lysshow stort": "Light show large",
  "Lyskæde varm hvid": "Fairy lights warm white",
  "Lyskæde farvet": "Fairy lights coloured",
  "Uplight": "Uplight",
  "Uplight 4-pak": "Uplight 4-pack",
  "Projektor": "Projector",
  "55\" Storskærm": "55\" Screen",
  "32\" Skærm": "32\" Screen",
  "Trådløs mikrofon PRO": "Wireless mic PRO",
  "Trådløst headset PRO": "Wireless headset PRO",
  "Håndholdt mikrofon (kabel)": "Handheld microphone (wired)",
  "Håndholdt mikrofon PRO (kabel)": "Handheld microphone PRO (wired)",
  "Projektor Pro (5000 lumen)": "Projector Pro (5000 lumen)",
  "Præsentationspakken": "Presentation bundle",
  "Konferencepakken": "Conference bundle",
  "Konferencepakke 150": "Conference package 150",
  "Speakerpakke trådløs 30-50": "Wireless speaker package 30-50",
  "Karaokemaskine": "Karaoke machine",
  "Karaokepakken": "Karaoke bundle",
  "Karaoke-festpakken": "Karaoke party bundle",

  "Mackie Mix12FX": "Mackie Mix12FX",
  "the t.mix xmix 1202 FXMP USB": "the t.mix xmix 1202 FXMP USB",
  "the t.mix xmix 1402 FXMP USB": "the t.mix xmix 1402 FXMP USB",
  "1 LED-lyseffekt uden stativ": "1 LED light effect without stand",
  "Røgmaskine inkl. væske": "Fog machine with fluid",
  "Lysbar på stativ": "Light bar on stand",
  // Højtalere og lyd
  '2× Alto 10" højtalere': '2× Alto 10" speakers',
  '2× EV 12" højtalere': '2× EV 12" speakers',
  '2× EV 12" højtalere + stativer': '2× EV 12" speakers + stands',
  '4× EV 12" højtalere': '4× EV 12" speakers',
  '2× 10" højtalere': '2× 10" speakers',
  '2× 12" højtalere': '2× 12" speakers',
  '12" subwoofer': '12" subwoofer',
  '2× 12" subwoofer': '2× 12" subwoofer',
  'Behringer 12" aktiv subwoofer': 'Behringer 12" powered subwoofer',
  'Mackie Thump GO 8"': 'Mackie Thump GO 8"',
  "Soundboks 4": "Soundboks 4",
  "Soundboks 4 (batteri)": "Soundboks 4 (battery)",
  "Højtalerstativer": "Speaker stands",
  "Stativer": "Stands",
  "2 sæt stativer": "2 sets of stands",
  "Stativ": "Stand",
  "3-fod stativ": "Tripod stand",
  "X-stativ": "X-stand",
  "1× EV ZLX 12P aktiv højtaler": "1× EV ZLX 12P powered speaker",
  "Ekstra batteri": "Spare battery",
  "Polstret bæretaske": "Padded carry bag",
  "Oplader": "Charger",
  "Bluetooth": "Bluetooth",

  // Mixere
  "4-kanals minimixer": "4-channel mini mixer",
  "Yamaha-mixer med indbyggede effekter": "Yamaha mixer with built-in effects",

  // Mikrofoner
  "Trådløs mikrofon": "Wireless microphone",
  "Trådløs mikrofon til talerne": "Wireless microphone for the speeches",
  "Trådløs håndholdt mic": "Wireless handheld mic",
  "Shure trådløs håndholdt mic": "Shure wireless handheld mic",
  "Shure trådløs mikrofon": "Shure wireless microphone",
  "Shure trådløs mikrofon PRO": "Shure wireless microphone PRO",
  "Shure BLX24/SM58 trådløs mikrofon": "Shure BLX24/SM58 wireless microphone",
  "Trådløs Shure-mikrofon": "Wireless Shure microphone",
  "Mikrofon med ledning": "Wired microphone",
  "Shure modtager": "Shure receiver",
  "Shure Beta 58A": "Shure Beta 58A",
  "Håndholdt mic": "Handheld mic",
  "Håndholdt mic + kabel": "Handheld mic + cable",
  "Håndholdt mikrofon med kabel": "Wired handheld microphone",
  "2 trådløse mikrofoner": "2 wireless microphones",
  "Headset-mikrofon": "Headset microphone",
  "PRO headset-mikrofon": "PRO headset microphone",
  "Trådløst headset": "Wireless headset",
  "Bodypack + modtager": "Bodypack + receiver",
  "Modtager": "Receiver",

  // Lys
  "1 LED-lyseffekt": "1 LED light effect",
  "2× LED-lyseffekt": "2× LED light effect",
  "2× farvet LED-lyseffekt": "2× coloured LED light effect",
  "2× farvede LED-lamper": "2× coloured LED lamps",
  "2× farvede LED-lamper + centereffekt på stativ": "2× coloured LED lamps + centre effect on a stand",
  "1× LED-par-lys (uden stativ)": "1× LED par light (no stand)",
  "Ekstra LED-par-lys": "Extra LED par light",
  "LED-par-lys med automatiske farveeffekter": "LED par light with automatic colour effects",
  "Centereffekt": "Centre effect",
  "Lysbar": "Light bar",
  "Lysbar (2 lamper + centereffekt)": "Light bar (2 lamps + centre effect)",
  "2× lysbar (2 lamper + centereffekt)": "2× light bar (2 lamps + centre effect)",
  "1× LED uplight": "1× LED uplight",
  "4× LED uplight": "4× LED uplight",
  "4× LED uplight til vægge og hjørner": "4× LED uplight for walls and corners",
  "Automatiske farver": "Automatic colours",
  "Automatiske farveeffekter": "Automatic colour effects",
  "LED-spot": "LED spotlight",
  "Motor": "Motor",
  "Discokugle 30 cm": "Disco ball 30 cm",
  "Discokugle 40 cm": "Disco ball 40 cm",
  "Discokugle 30 cm med motor og spot": "Disco ball 30 cm with motor and spotlight",
  "Discokugle 40 cm med motor og spot": "Disco ball 40 cm with motor and spotlight",
  "Discokugle med motor og spot": "Disco ball with motor and spotlight",
  "Discokugle 40 cm med motor, stativ og spot": "Disco ball 40 cm with motor, stand and spotlight",
  "Discokugle 40 cm guld": "Disco ball 40 cm gold",
  "Stativ/ophæng": "Stand or hanging kit",
  "Stativ/ophæng til kuglen": "Stand or hanging kit for the ball",
  "10 m lyskæde": "10 m fairy lights",
  "10m lyskæde": "10 m fairy lights",
  "10 m lyskæde varm hvid": "10 m fairy lights, warm white",
  "10 m lyskæde farvet": "10 m fairy lights, coloured",
  "10 m farvet lyskæde": "10 m coloured fairy lights",
  "Varm hvide pærer": "Warm white bulbs",
  "Farvede pærer": "Coloured bulbs",
  "Indbygget skærm + festlys": "Built-in screen + party lights",
  "Botex SP-1500 DMX stroboskop": "Botex SP-1500 DMX strobe light",
  "Controller": "Controller",
  "4× LED PAR": "4× LED PAR",
  "Stativ med tværbom": "Stand with T-bar",
  "LED-følgespot 120 W": "LED follow spot 120 W",
  "LED UV-lampe": "LED UV light",
  "RGB-laser": "RGB laser",

  // Røg
  "Røgmaskine": "Fog machine",
  "Røgmaskine + væske": "Fog machine + fluid",
  "Røgmaskine med væske": "Fog machine with fluid",
  "Røgvæske": "Fog fluid",
  "Low fog-maskine": "Low fog machine",
  "Low fog-maskine (røggulv)": "Low fog machine (fog floor)",
  "Low fog-maskine med væske og is-instruks": "Low fog machine with fluid and ice instructions",
  "Is-bakke / instruks": "Ice tray / instructions",
  "Snemaskine": "Snow machine",
  "Snevæske": "Snow fluid",
  "Sæbeboblemaskine": "Bubble machine",
  "Boblevæske": "Bubble fluid",

  // Skærm, projektor og lærred
  "Full HD projektor": "Full HD projector",
  "5000 lumen projektor": "5000 lumen projector",
  '32" LED-skærm': '32" LED screen',
  '55" LED-skærm': '55" LED screen',
  '32" LED-skærm på 3-fod stativ': '32" LED screen on a tripod stand',
  '55" LED-skærm på 3-fod stativ': '55" LED screen on a tripod stand',
  '55" skærm + stativ': '55" screen + stand',
  '55" skærm på stativ': '55" screen on a stand',
  "160 cm lærred": "160 cm projector screen",
  "Lærred 160 cm": "160 cm projector screen",
  "Lærred 160 cm på stativ": "160 cm projector screen on a stand",
  "Fjernbetjening": "Remote control",

  // Karaoke
  "Singing Machine karaoke-maskine": "Singing Machine karaoke machine",
  "Singing Machine + 2 trådløse mikrofoner": "Singing Machine + 2 wireless microphones",

  // Kabler og strøm
  "Alle kabler": "All cables",
  "Alle kabler + strøm": "All cables + power",
  "Bluetooth + alle kabler": "Bluetooth + all cables",
  // Lydmand og pakkerne med lydmand (11. sept 2026)
  "AV-tekniker på stedet": "AV technician on site",
  "AV-tekniker på stedet i 4 timer": "AV technician on site for 4 hours",
  "Opsætning og lydprøve": "Setup and sound check",
  "Styrer lyd og mikrofoner under festen": "Runs sound and microphones during the event",
  "Lydmand i 4 timer": "Sound engineer for 4 hours",
  "Levering, opsætning og afhentning": "Delivery, setup and collection",
  "Yamaha-mixer med effekter": "Yamaha mixer with effects",
  'Subwoofer 12"': '12" subwoofer',
  "Lysbar + røgmaskine": "Light bar + fog machine",
  "HDMI + alle kabler": "HDMI + all cables",
  "HDMI + strøm": "HDMI + power",
  "HDMI-kabel": "HDMI cable",
  "HDMI-kabel + Bluetooth": "HDMI cable + Bluetooth",
  // Forespørgselsvarerne, tilføjet 22. september 2026
  "Maskine med to kamre": "A machine with two bowls",
  "Sirup efter aftale": "Syrup as agreed",
  "Krus og sugerør kan følge med": "Cups and straws can come with it",
  "Almindelig 230 V": "Ordinary 230 V mains",
  "Køleanlæg med hane": "Cooling unit with a tap",
  "Kulsyre og slanger": "CO2 and lines",
  "Fustage efter aftale": "Keg as agreed",
  "Vejledning ved levering": "A run-through on delivery",
  "AUX-kabel": "AUX cable",
  "AUX + strømkabler": "AUX + power cables",
  "Oplader + AUX-kabel": "Charger + AUX cable",
  "Kabel til højtaler": "Cable to the speaker",
  "Kabler til højtaler": "Cables to the speaker",
  "Kabelforbindelse": "Cable connection",
  "Kabelforbindelse til højtaler": "Cable connection to the speaker",
  "Kabler + adapter": "Cables + adapter",
  "Signalkabel til højtalere": "Signal cable to the speakers",
  "Stativer og kabler": "Stands and cables",
  "Stativ og kabler": "Stand and cables",
  "Strøm og kabler": "Power and cables",
  "Strøm + DMX/kabler": "Power + DMX cables",
  "Strømkabel": "Power cable",
  "Strømkabler": "Power cables",
  "Strømforsyning": "Power supply",
  "XLR/kabel": "XLR cable",
  "USB-C / iPhone-adapter": "USB-C / iPhone adapter",
  "Plug and play": "Plug and play",
  // Produktarket 19. sept 2026: modelnavne i indholdslinjerne
  "2× Alto TX 410 10\" højtalere": "2× Alto TX 410 10\" speakers",
  "2× EV ZLX 12P G2 12\" højtalere": "2× EV ZLX 12P G2 12\" speakers",
  "Behringer B1200D Pro subwoofer": "Behringer B1200D Pro subwoofer",
  "Behringer B1200D Pro aktiv 12\" subwoofer": "Behringer B1200D Pro powered 12\" subwoofer",
  "Eurolite LED Mini Z-20 beam-effekt": "Eurolite LED Mini Z-20 beam effect",
  "USB-strømkabel": "USB power cable",
  "Automatiske effekter": "Automatic effects",
  "2× Fun Generation PartyPar 12 LED": "2× Fun Generation PartyPar 12 LED",
  "4× Fun Generation PartyPar 12 LED": "4× Fun Generation PartyPar 12 LED",
  "1× Fun Generation PartyPar 12 LED": "1× Fun Generation PartyPar 12 LED",
  "ADJ Mini Dekker centereffekt": "ADJ Mini Dekker centre effect",
  "Strøm + kabler": "Power + cables",
  "Eliminator VF1300 EP røgmaskine": "Eliminator VF1300 EP fog machine",
  "Eurolite NB-60 ICE low fog-maskine": "Eurolite NB-60 ICE low fog machine",
  "Eliminator VF Flurry EP snemaskine": "Eliminator VF Flurry EP snow machine",
  "Eurolite SD201 DMX sæbeboblemaskine": "Eurolite SD201 DMX bubble machine",
  "2× højtalerstativ, Millenium BS-2211B": "2× speaker stand, Millenium BS-2211B",
  "Bæretaske til stativerne": "Carry bag for the stands",
  "Soundboks batteri (USB-C)": "Soundboks battery (USB-C)",
  "Opladet ved afhentning": "Charged at pickup",
  "the t.bone MB 60": "the t.bone MB 60",
  "XLR-kabel": "XLR cable",
  "Stairville Mini T-Bar 2": "Stairville Mini T-Bar 2",
  "Gravity KSX 2 X-stativ": "Gravity KSX 2 X-stand",
  "Gravity KSX 2 RD Set: X-stativ med sort klæde": "Gravity KSX 2 RD Set: X-stand with black cloth",
  "1× EV ZLX 12P G2 aktiv højtaler": "1× EV ZLX 12P G2 powered speaker",
  "Eurolite Mirror Ball 40 cm gold": "Eurolite Mirror Ball 40 cm gold",
  "Stageworx TS-120 tværbom på stativ": "Stageworx TS-120 cross bar on a stand",
  "Showtec Professional Mirrorball 40 cm": "Showtec Professional Mirrorball 40 cm",
  "Showtec Professional Mirrorball 30 cm": "Showtec Professional Mirrorball 30 cm",
  "Stairville Wild Wash 9×3 W LED UV": "Stairville Wild Wash 9×3 W LED UV",
  "Laserworld EL-230RGB MKII": "Laserworld EL-230RGB MKII",
  "Showtec Followspot LED 120 W": "Showtec Followspot LED 120 W",
  "Shure BLX14 med PGA31 headset": "Shure BLX14 with PGA31 headset",
};

/**
 * Pakkelisten på sidens sprog.
 *
 * Ukendte linjer beholder deres danske ordlyd, en teknisk delbetegnelse er
 * stadig oplysning, og et tomt punkt er ikke.
 */
export function contentsFor(contents: string[] | undefined, locale: Locale): string[] {
  if (!contents?.length) return [];
  if (locale !== "en") return contents;
  return contents.map((c) => CONTENTS_EN[c] ?? c);
}
