import type {Metadata} from 'next';
import Link from 'next/link';
import ProductLanding from '@/components/ProductLanding';
import BundleGrid from '@/components/BundleGrid';
import {localeAlternates} from '@/lib/hreflang';
export const metadata:Metadata={title:'Lej DJ-pult | AlphaTheta XDJ | 1.695 kr',description:'Lej en AlphaTheta XDJ, et all-in-one DJ-system uden computer. Vælg pulten alene eller en lille, mellem eller stor DJ-pakke med højtalere. 1.695 kr inklusive moms.',alternates:{canonical:'https://lejhojtaler.dk/dj-pult',languages:localeAlternates('/dj-pult')}};
export default function Page(){return <ProductLanding slug="dj-pult" name="DJ-pult · AlphaTheta XDJ" price={1695} headline="Jeres musik. Jeres DJ-pult." sub="AlphaTheta XDJ all-in-one DJ-system. Spil fra USB, ingen computer. Lej pulten alene, eller vælg en pakke med højtalere og lys." image="/images/product-dj-pult-white.webp" imageAlt="AlphaTheta XDJ all-in-one DJ-pult på hvid baggrund" productId="dj_pult" bookLabel="Læg DJ-pult i kurven" bullets={['AlphaTheta XDJ all-in-one DJ-pult','DJ-hovedtelefoner · Fun Generation HP 5 medfølger','Tilslutningskabler medfølger','Spotify via djay. Spotify Premium kræves','','DJ/musikafvikler vælges separat efter antal timer']} faqMode="extraOnly" faqExtra={[{q:'Er der en DJ med?',a:'Prisen gælder leje af udstyret. En DJ/musikafvikler kan tilvælges fra 3 timer på DJ-siden.'},{q:'Kan Spotify bruges til alle arrangementer?',a:'Spotify-musikken er kun til privat brug. Til offentlige og erhvervsmæssige arrangementer skal musikkilden være egnet til den brug. Aftal musikken med DJ’en.'}]}>
 <BundleGrid ids={["dj_pakke_lille", "dj_pakke_mellem", "dj_pakke_stor"]} title="Vælg gear fra lille til stor" subtitle="Alle pakker indeholder DJ-pulten. DJ-timer tilvælges separat. Priser inklusive moms."/>
 <p className="mx-auto max-w-5xl px-6 py-8 text-center"><Link className="font-semibold text-brand-600" href="/dj">Tilvælg DJ/musikafvikler og indtast timer →</Link></p>
 </ProductLanding>;}
