import type {Metadata} from 'next';
import Link from 'next/link';
import ProductLanding from '@/components/ProductLanding';
import BundleGrid from '@/components/BundleGrid';
import {localeAlternates} from '@/lib/hreflang';
export const metadata:Metadata={title:'Lej DJ-pult | Pioneer DDJ-FLX4 med iPad | 1.995 kr',description:'Lej en Pioneer DDJ-FLX4 med iPad i flightcase. Vælg pulten alene eller en lille, mellem eller stor DJ-pakke med højtalere. 1.995 kr inklusive moms.',alternates:{canonical:'https://lejhojtaler.dk/dj-pult',languages:localeAlternates('/dj-pult')}};
export default function Page(){return <ProductLanding slug="dj-pult" name="DJ-pult · Pioneer DDJ-FLX4" price={1995} headline="Jeres musik. Jeres DJ-pult." sub="Pioneer DDJ-FLX4 med iPad i flightcase og DJ-hovedtelefoner. Lej pulten alene, eller vælg en pakke med højtalere og lys." image="/images/product-dj-flx4-white.webp" imageAlt="Pioneer DDJ-FLX4 med iPad i flightcase på hvid baggrund" productId="dj_pult" bookLabel="Læg DJ-pult i kurven" bullets={['Pioneer DDJ-FLX4 med iPad og flightcase','DJ-hovedtelefoner · Fun Generation HP 5 medfølger','Tilslutningskabler medfølger','Spotify via djay. Spotify Premium kræves','Bemærk: Kræver internetforbindelse på din iPad under afspilning, og musikken er kun til privat brug.','DJ/musikafvikler vælges separat efter antal timer']} faqMode="extraOnly" faqExtra={[{q:'Er der en DJ med?',a:'Prisen gælder leje af udstyret. En DJ/musikafvikler kan tilvælges fra 3 timer på DJ-siden.'},{q:'Kan Spotify bruges til alle arrangementer?',a:'Spotify-musikken er kun til privat brug. Til offentlige og erhvervsmæssige arrangementer skal musikkilden være egnet til den brug. Aftal musikken med DJ’en.'}]}>
 <BundleGrid ids={["dj_pakke_lille", "dj_pakke_mellem", "dj_pakke_stor"]} title="Vælg gear fra lille til stor" subtitle="Alle pakker indeholder DJ-pult med iPad i flightcase. DJ-timer tilvælges separat. Priser inklusive moms."/>
 <p className="mx-auto max-w-5xl px-6 py-8 text-center"><Link className="font-semibold text-brand-600" href="/dj">Tilvælg DJ/musikafvikler og indtast timer →</Link></p>
 </ProductLanding>;}
