import {describe,it,expect,beforeEach,afterEach,vi} from 'vitest';
import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import EventHeroGallery from '@/components/EventHeroGallery';
import BookingFlow from '@/components/BookingFlow';
import {requireDjGear,DJ_ID} from '@/lib/dj';
import {djGearProducts} from '@/lib/djGearProducts';
import {buildLineItems,loadPriceTable} from '../../functions/api/_lib/pricing';
import {vælgDatoer} from './vaelgDatoer';
beforeEach(()=>{vi.clearAllMocks();(global.fetch as any).mockResolvedValue({ok:true,json:async()=>({inventory:{},booked:{},blocked_dates:[]})});});
afterEach(()=>{cleanup();window.history.pushState({},'', '/');});
it('skifter opstilling med klik og løber tilbage til første billede',()=>{render(<EventHeroGallery locale="da"/>);const button=screen.getByRole('button',{name:'Vis næste opstilling'});expect(screen.getByRole('img')).toHaveAttribute('src','/images/events/reception-detail.webp');fireEvent.click(button);expect(screen.getByRole('img')).toHaveAttribute('src','/images/events/reception-front.webp');for(let i=0;i<4;i++)fireEvent.click(button);expect(screen.getByRole('img')).toHaveAttribute('src','/images/events/reception-detail.webp');});
it('kræver gear til DJ og regner det som en separat vare på serveren',async()=>{expect(()=>requireDjGear([DJ_ID])).toThrow();expect(()=>requireDjGear([DJ_ID,'dj_pult'])).not.toThrow();const table=await loadPriceTable({get:async()=>null} as unknown as KVNamespace);expect(()=>buildLineItems(table,[{id:DJ_ID,dj:{before23:3,after23:0}}])).toThrow();expect(buildLineItems(table,[{id:DJ_ID,dj:{before23:3,after23:0}},{id:'dj_pult'}]).totalOre).toBe(469500);/* produktarket 17. sept 2026: DJ 3000 + dj_pult 1695 (før 1995) */for(const p of djGearProducts.filter(p=>p.bundle))expect(p.bundle!.parts.some(part=>part.productId==='dj_pult')).toBe(true);});
it('bevarer valgt DJ-gear og timepris i kurven og ved skift af udstyr',async()=>{window.history.pushState({},'', '/?product=dj_musikafvikler&djBefore=2&djAfter=2&djGear=dj_pakke_lille#book');const summary=vi.fn();render(<BookingFlow onSummaryChange={summary}/>);await waitFor(()=>expect(screen.getByText('Vælg datoer')).toBeInTheDocument());const small=djGearProducts.find(p=>p.id==='dj_pakke_lille')!;await waitFor(()=>expect(summary).toHaveBeenLastCalledWith(expect.objectContaining({total:5000+small.price})));vælgDatoer();await waitFor(()=>expect(screen.getByText('Videre')).not.toBeDisabled());fireEvent.click(screen.getByText('Videre'));expect(screen.getByRole('radio',{name:/DJ Pakke 0-30/}/* produktarket 17. sept 2026: før "Lille DJ-pakke" */)).toBeChecked();fireEvent.click(screen.getByRole('radio',{name:/DJ-pult · Pioneer/}));await waitFor(()=>expect(summary).toHaveBeenLastCalledWith(expect.objectContaining({total:6695})/* 5000 + dj_pult 1695 */));expect(screen.getByRole('spinbutton',{name:/Timer før kl. 23/})).toHaveValue(2);});

it("viser gemt åbningstidstekst uden em dash og på engelsk",async()=>{const {otherLine,DEFAULT_OPENING_HOURS}=await import("@/lib/openingHours");const hours={...DEFAULT_OPENING_HOURS,other:"Andre tidspunkter efter aftale — skriv i kommentarfeltet ved booking."};expect(otherLine(hours)).not.toContain("—");expect(otherLine(hours,"en")).toBe("Other times by arrangement. Add a note when booking.");});
