import Link from "next/link";
import { eventSituations, situationImageIsProduct, situationImageSrc } from "@/lib/eventSituations";
import { localizedHref } from "@/lib/enPages";
import type { Locale } from "@/lib/i18n";
import BundleGrid from "./BundleGrid";
import GoogleReviews from "./GoogleReviews";
import Footer from "./Footer";
import EventInquiryForm from "./EventInquiryForm";
import styles from "./EventHome.module.css";
import SituationDirectory from "./SituationDirectory";
import { DJ_HOUR_RATE } from "@/lib/dj";
import { anledningPaaPause } from "@/lib/products";
export default function SituationPage({slug,locale}:{slug:string;locale:Locale}) {
 const s=eventSituations.find(s=>s.slug===slug)!; const c=s[locale];const en=locale==="en";
 // Alle anledningens pakker bygger på skærm eller projektor, som er ude af
 // sortimentet (28. sept 2026). Siden bliver liggende, men siger det.
 const pause=anledningPaaPause(slug);
 return <main className={styles.page} lang={locale}>
 <section className={`${styles.hero} ${styles.compactHero}`}><div className={styles.heroCopy}><Link href={localizedHref('/eventloesninger',locale)} className={styles.location}>{en?"All event solutions":"Alle eventløsninger"}</Link><h1>{c.title}</h1><p className={styles.lead}>{c.lead}</p><p>{c.body}</p><div className={styles.actions}>{pause?<Link href={localizedHref("/eventloesninger",locale)} className={styles.primary}>{en?"See other occasions":"Se andre anledninger"}</Link>:<a href="#pakker" className={styles.primary}>{en?"Compare packages":"Se pakker og priser"}</a>}<a href={localizedHref("/av-udstyr",locale)} className={styles.textLink}>{en?"Browse equipment":"Se enkeltprodukter"}</a></div></div><figure className={`${styles.heroImage} ${situationImageIsProduct(s.image)?styles.productHero:""}`}><img src={situationImageSrc(s.image)} width="1200" height="800" alt={en?"Equipment for this occasion":"Udstyr til anledningen"}/><figcaption>{situationImageIsProduct(s.image)?(en?"The equipment, ready to book":"Udstyret, klar til at booke"):s.image==='reception-front-v2'?(en?"Photo of an actual setup":"Foto af en konkret opstilling"):(en?"Illustrative setup":"Illustreret opstilling")}</figcaption></figure></section>
 {pause?<section id="pakker" className={styles.section}><div className={styles.sectionHead}><h2>{en?"This equipment is not available right now.":"Udstyret her udlejes ikke lige nu."}</h2><p>{en?"These packages are built around a screen or projector, which we have taken out of the range for now. Sound, microphones and lighting can still be booked online.":"Pakkerne her bygger på skærm eller projektor, som vi har taget ud af sortimentet indtil videre. Lyd, mikrofoner og lys kan stadig bookes online."}</p></div><div className={styles.actions}><Link className={styles.primary} href={localizedHref("/lej-mikrofon",locale)}>{en?"See microphones":"Se mikrofoner"}</Link><Link className={styles.textLink} href={localizedHref("/lej-hojtaler",locale)}>{en?"See speakers":"Se højtalere"} →</Link></div></section>:<BundleGrid locale={locale} ids={[...s.packageIds]} title={en?"Choose your equipment package":"Vælg jeres udstyrspakke"} subtitle={en?"Equipment prices include VAT. Delivery, setup and staffing are selected separately. Final suitability depends on your venue and programme.":"Udstyrspriser inklusive moms. Levering, opsætning og bemanding tilvælges separat. Den endelige løsning afhænger af lokale og program."}/>}
 {s.dj&&<BundleGrid locale={locale} sectionId="dj-pakker" ids={["dj_pakke_lille","dj_pakke_mellem","dj_pakke_stor"]} title={en?"DJ equipment packages":"Pakker med DJ-pult"} subtitle={en?"AlphaTheta XDJ all-in-one DJ system included, no laptop needed. Choose the sound and lighting size. DJ hours are separate.":"AlphaTheta XDJ all-in-one DJ-pult er med, ingen computer nødvendig. Vælg størrelse på lyd og lys. DJ-timer tilvælges separat."}/>}
 {s.dj&&<section className={styles.equipment}><h2>{en?"Let a DJ take care of the music.":"Lad en DJ tage sig af musikken."}</h2><p>{en?`Set start and finish. DKK ${DJ_HOUR_RATE.toLocaleString("en-GB")}/hour, always, including VAT. Delivery, setup and collection are in the DJ price. Add lights and a larger sound system by guest count.`:`Sæt start og sluttid. ${DJ_HOUR_RATE.toLocaleString("da-DK")} kr/time, altid, inklusive moms. Levering, opsætning og nedtagning er med i DJ-prisen. Tilvælg lys og et større musikanlæg efter antal gæster.`}</p><Link className={styles.primary} href={localizedHref('/dj',locale)}>{en?"Get a DJ quote":"Få et DJ-tilbud"}</Link></section>}
 <section className={styles.section}><div className={styles.sectionHead}><h2>{en?"Plan the practical details.":"Få styr på det praktiske."}</h2><p>{en?"These details help us choose and position the equipment.":"De her afklaringer hjælper os med at vælge og placere udstyret."}</p></div><ul className="grid gap-5 md:grid-cols-3">{c.check.map(t=><li className="border-l-2 border-brand-500 pl-5 text-lg" key={t}>{t}</li>)}</ul></section>
 <section className={styles.shopHelp}><div><h2>{en?"Need help choosing?":"Brug for hjælp til at vælge?"}</h2><p>{en?"Ask us about the equipment, delivery or setup.":"Spørg os om udstyret, levering eller opsætning."}</p></div><details id="foresp"><summary className="cursor-pointer font-semibold text-brand-600">{en?"Ask a question":"Stil et spørgsmål"}</summary><div className="mt-5 max-w-xl"><EventInquiryForm locale={locale} initialSituation={slug}/></div></details></section>
 <GoogleReviews locale={locale}/><SituationDirectory locale={locale}/><Footer locale={locale}/></main>;
}
