import type {Metadata} from 'next';
import Link from 'next/link';
import ProductLanding from '@/components/ProductLanding';
import BundleGrid from '@/components/BundleGrid';
import {localeAlternates} from '@/lib/hreflang';
export const metadata:Metadata={title:'DJ system rental Copenhagen | AlphaTheta XDJ | DKK 1,695',description:'Hire an AlphaTheta XDJ, an all-in-one DJ system with no laptop needed. Choose the controller on its own or a small, medium or medium speaker package. VAT included.',alternates:{canonical:'https://lejhojtaler.dk/en/dj-pult',languages:localeAlternates('/dj-pult')}};
export default function Page(){return <ProductLanding locale="en" slug="dj-pult" name="DJ system · AlphaTheta XDJ" price={1695} headline="Your music. Your DJ setup." sub="AlphaTheta XDJ all-in-one DJ system. Play from USB, no laptop. Hire the system on its own or choose a package with speakers and lighting." image="/images/product-dj-flx4-white.webp" imageAlt="Pioneer DDJ-FLX4 with an iPad in a flight case on white" productId="dj_pult" bookLabel="Add DJ controller to basket" bullets={['Pioneer DDJ-FLX4 with iPad and flight case','Fun Generation HP 5 DJ headphones included','Connection cables included','Spotify via djay. Spotify Premium required','Note: Your iPad needs an internet connection during playback, and the music is for private use only.','Hire a DJ/music host separately by the hour']} faqMode="extraOnly" faqExtra={[{q:'Is a DJ included?',a:'The price covers equipment hire. Add a DJ/music host for a minimum of 3 hours on our DJ page.'},{q:'Can Spotify be used for every event?',a:'Spotify music is for private use only. Public and business events require a music source suitable for that use. Agree the music with your DJ.'}]}>
 <BundleGrid locale="en" ids={["dj_pakke_lille", "dj_pakke_mellem", "dj_pakke_stor"]} title="Choose small, medium or large" subtitle="Every package includes the DJ controller with an iPad in a flight case. DJ hours are hired separately. VAT included."/>
 <p className="mx-auto max-w-5xl px-6 py-8 text-center"><Link className="font-semibold text-brand-600" href="/en/dj">Add a DJ/music host and enter your hours →</Link></p>
 </ProductLanding>;}
